#!/usr/bin/env node
'use strict';

/**
 * Regression test for BUG-1 in docs/STATUS.md — "the backend admin UI will not
 * build on Windows".
 *
 * WHAT IT CHECKS
 * Keystone's admin UI generator writes
 * `.keystone/admin/pages/api/__keystone_api_build.js`, whose whole job is to
 * re-export the project's Keystone config so `keystone-next start` (and the
 * admin UI's own api route) can load it:
 *
 *     export { default as config } from '<path to backend/keystone>'
 *
 * @keystone-next/admin-ui 8.0.2 builds that path with `Path.relative()`, which
 * returns BACKSLASH separators on Windows, and interpolates the result straight
 * into the import specifier without normalising it. JavaScript then reads the
 * backslashes as string escapes, so `..\..\..\..\keystone` is written out and
 * compiled as the module id `........keystone` — which resolves to nothing:
 *
 *     export { default as config } from '........keystone';
 *
 * The admin UI build then dies with
 *     Module not found: Can't resolve '........keystone'
 * so `npm run build` (and therefore `npm run start`) fails on Windows only.
 * CI is green because the build runs on ubuntu-latest, where Path.relative()
 * already returns forward slashes.
 *
 * THE FIX lives in patches/@keystone-next+admin-ui+8.0.2.patch (applied by
 * patch-package from the `postinstall` script), mirroring the separator
 * normalisation the same function already applies to user-supplied admin pages.
 *
 * RED before the fix · GREEN after it.
 *
 * RUN
 *   npm run test:admin-ui-import
 *
 * PRECONDITION
 * The file under test is generated, not committed. Generate it with
 * `npm run dev` (it is written a couple of minutes in, before the long admin-UI
 * compile starts — you can kill the server once it appears) or `npm run build`.
 */

const fs = require('fs');
const path = require('path');

const BACKEND = path.resolve(__dirname, '..');
const ADMIN_API_DIR = path.join(BACKEND, '.keystone', 'admin', 'pages', 'api');
const GENERATED = path.join(ADMIN_API_DIR, '__keystone_api_build.js');
const CONFIG_STEM = path.join(BACKEND, 'keystone');
const EXTENSIONS = ['.ts', '.tsx', '.js', '.jsx', '.json'];

function fail(message) {
  console.error(`FAIL: ${message}`);
  process.exit(1);
}

if (!fs.existsSync(GENERATED)) {
  console.error(`Cannot find ${GENERATED}`);
  console.error(
    'That file is generated by Keystone and is not committed. Run `npm run dev`\n' +
      '(it appears early, well before the slow admin-UI compile finishes) or\n' +
      '`npm run build`, then re-run this test.'
  );
  process.exit(2);
}

const source = fs.readFileSync(GENERATED, 'utf8');
const match = source.match(/export\s*\{\s*default\s+as\s+config\s*\}\s*from\s*'([^']*)'/);
if (!match) {
  fail(`no "export { default as config } from '...'" statement in ${GENERATED}`);
}
const specifier = match[1];

// 1. The specifier must be a relative POSIX path: `./x` or one or more `../`
//    followed by a plain segment. This is the assertion the bug trips.
if (!/^(?:\.\.?\/)+[A-Za-z0-9._-]+$/.test(specifier)) {
  fail(
    `the generated import specifier is ${JSON.stringify(specifier)}, which is not a\n` +
      'relative forward-slash module path.\n' +
      "On Windows Keystone's generator interpolates Path.relative() output raw, so\n" +
      "backslash separators are eaten as JS escapes and '../../../../keystone'\n" +
      "becomes '........keystone'. Check that patches/@keystone-next+admin-ui+8.0.2.patch\n" +
      'was applied by `npm ci` (postinstall runs patch-package).'
  );
}

// 2. It must be exactly the path from the generated file's directory to the
//    project's Keystone config (extension resolved by the bundler).
const expected = path.relative(ADMIN_API_DIR, CONFIG_STEM).split(path.sep).join('/');
if (specifier !== expected) {
  fail(`the specifier is ${JSON.stringify(specifier)}; expected ${JSON.stringify(expected)}`);
}

// 3. And the file it names must actually exist on disk.
const target = path.resolve(ADMIN_API_DIR, specifier);
if (!target.startsWith(BACKEND)) {
  fail(`the specifier resolves outside the backend package: ${target}`);
}
const resolved = EXTENSIONS.map((ext) => target + ext).find((file) => fs.existsSync(file));
if (!resolved) {
  fail(
    `the specifier resolves to ${target}, but no file exists there\n` +
      `(looked for ${EXTENSIONS.join(', ')})`
  );
}

console.log(`PASS: __keystone_api_build.js imports '${specifier}' -> ${resolved}`);
